TITLE="Beej's Guide to Python Programming"
SUBTITLE="For Beginners"
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v0.0.11, Copyright © August 27, 2024"

GUIDE_ID=bgpython

BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard *.png *.svg)

include $(BGBSPD_BUILD_DIR)/source.make
